# @package hydra.launcher

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 4320
cpus_per_task: 6
gpus_per_node: ${gpus}
tasks_per_node: 1
mem_gb: 20
nodes: 1
name: ${hydra.job.name}
partition: das
comment: null
constraint: null
exclude: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: { "mail-user": "nvaessen", "mail-type": "BEGIN,END,FAIL" }
array_parallelism: 4
